name: Build and deploy to AWS
on: 
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      with:
        # Repository name with owner. For example, actions/checkout
        repository: ${{ github.repository }}

    - name: Setup Node
      uses: actions/setup-node@v3.8.1
      with:
          node-version: 18.17.x
          cache: npm

    - name: Install node modules 
      run: npm install

    - name: Build node modules
      run: npm run build

    - name: Install composer dependencies
      uses: baschny/php-composer-action@v1
      with:
        # What version of Composer to use
        command: install
    
    - name: Compress action step
      uses: a7ul/tar-action@v1.1.0
      id: compress
      with:
        command: c
        cwd: ./portfolio-laravel
        files: |
          ./*
          outPath: potfolio-laravel.tar.gz
          
    - name: SCP Files
      uses: appleboy/scp-action@v0.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: portfolio-laravel.tar.gz
        target: ~/

    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PORTFOLIO_SECRET }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          echo "Nice Job!!!"
