name: Build & Deploy
on: [push]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 52.201.52.30
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PORTFOLIO_SECRET }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          echo "Nice Job!!!"
