name: Build & Deploy
on: 
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      with:
        # Repository name with owner. For example, actions/checkout
        repository: ${{ github.repository }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
          node-version: 18.17.x
          cache: npm

    - name: Install node modules 
      run: npm install

    - name: Build node modules
      run: npm run build

    - name: Install composer dependencies
      uses: baschny/php-composer-action@v1
      with:
        # What version of Composer to use
        command: install
      
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 52.201.52.30
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PORTFOLIO_SECRET }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          echo "Nice Job!!!"
